### ISSUE TITLE
WAILA errors and more console spam

### ISSUE THREAD

**Issue by Revemohl** [elytra/FruitPhone#7] opened 2017-03-06 12:29 UTC
Found another noisy problem on 1.7.10, using the same test instance as the other issue I submitted (#6) but now with the addition of Waila-1.5.10_1.7.10.jar. The problem is simple, just look at any mob spawner and you'll get [this screencap](http://i.imgur.com/7lU4tKS.png) while this gets spammed all over the console: https://gist.github.com/Revemohl/fe0a644e600823f760322dde00f4df17

And while I'm talking about WAILA, I've noticed that [Fruit Phone is ignoring entities, or at least ignoring WAILA while looking at entities](http://i.imgur.com/OSg0RML.png) (note how the mod name isn't shown in that case, but it does show up if I'm looking directly at a grass block). Is that intentional?

In any case, here's the full latest log again: https://gist.github.com/Revemohl/d9ead035d8c40778aa742e257aeb4bce

**Comment by exaskye** [comment] 2017-03-06 13:38
Fruit Phone does not currently show entity information. Since it shares the game's objectMouseOver raytrace for Waila lookups, this means it will be occluded by them. In the future it'll have entity support.

[Made a quick build with an experimental fix](https://unascribed.com/f/428ff28d_FruitPhone-1.7.10-0.1.6-exp1.jar); let me know if it does indeed fix the issue.

**Comment by Fortist** [comment] 2017-03-07 00:09
I had a similar issue with Logistics pipes, looking at the requesting crafting table, and tooltip gets larger.
![2017-03-06_19 05 01](https://cloud.githubusercontent.com/assets/5784537/23635919/67a583c0-02a0-11e7-8817-0f2cc94e9391.png)

**Comment by Revemohl** [comment] 2017-03-07 06:13
Looks like the experimental build works, but it does so [by not rendering the Fruit Phone thingy at all when you look at a spawner](http://i.imgur.com/9bTj1pg.png).

(edit) This happens while looking at a Thaumcraft aura node as well.

**Comment by exaskye** [comment] 2017-03-07 13:20
Yeah, that's what I figured would happen. I'll try for a proper fix soon.

**Comment by exaskye** [comment] 2017-03-16 00:10
So I'm not quite sure how I should go about fixing this; the root of the problem is that the item has no pickblock, and there's no Waila plugin giving me a better itemstack. The experimental fix is probably the best I can do.

**Comment by exaskye** [comment] 2017-03-16 01:29
Fix published as [v0.1.7 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.7), [v0.1.7 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.7), and [v0.1.7 (1.7.10)](https://github.com/elytra/FruitPhone/releases/tag/1.7.10-0.1.7).

**Comment by BBoldt** [comment] 2017-07-19 04:52
Now in 1.12:
https://vid.me/EKZOs

Forge 2415
Hwyla 1.8.19-B33_1.12
Fruit Phone 1.12-2.75

**Comment by exaskye** [comment] 2017-07-19 05:05
wat

**Comment by LemmaEOF** [comment] 2017-10-29 19:15
I'm getting the same issue in 1.12.2 as well, looking at portal blocks.
![2017-10-28_01 08 47](https://user-images.githubusercontent.com/6722691/32147319-aaeacb4c-bca2-11e7-8688-30a130cd5f35.png)

Forge 2491
Hwyla 1.8.20_B35_1.12
FruitPhone 1.12-2.75

**Comment by exaskye** [comment] 2018-04-27 12:46
Fixed by #30

**Closed as completed by exaskye** 2018-04-27 12:46 UTC
Labels: k: Bug
