### ISSUE TITLE
Configuration GUI Crash

### ISSUE THREAD

**Issue by Fortist** [elytra/FruitPhone#8] opened 2017-03-07 00:14 UTC
-  0.1.6 Phone or whatever
- 1.7.10
- Seeing as forge doesnt update anymore, THE LATEST. 1614
Crash report.
http://pastebin.com/a1G6GMZf

While configuring the GUI location and clicking on the CHEST configuration part, it crashed. Im assuming its because it was picking random items to put into the chest, and some items are bad (Missing textures or placeholder stuff) and they shouldnt be picked.

**Comment by exaskye** [comment] 2017-03-07 00:52
...I thought I fixed this crash.

**Comment by smithnc07** [comment] 2017-03-09 21:29
Adding to this: 
Testing with MC 1.10.2 
Forge: 12.18.3.2254
FruitPhone-1.10.2-0.1.3.jar
ProbeDataProviderAPI-MC1.10.2_ver1.1.1.jar

I also crash when using the power drill.
(Specifically if not wearing any glasses. If I'm wearing glasses it works just fine.) 

java.lang.NullPointerException: Rendering screen
	at com.elytradev.fruitphone.client.gui.ScreenConfigureGlasses.func_73863_a(ScreenConfigureGlasses.java:307)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by exaskye** [comment] 2017-03-09 21:30
@smithnc07, your issue is a duplicate of #3 which has been fixed.

**Comment by smithnc07** [comment] 2017-03-09 21:45
Whoops, my apologies, I didn't noticed I had an outdated release. Thank you.

**Closed as completed** 2017-03-16 00:09 UTC
Labels: k: Bug

**Comment by exaskye** [comment] 2017-03-16 01:29
Fix published as [v0.1.7 (1.11.2)](https://github.com/elytra/FruitPhone/releases/tag/1.11.2-0.1.7), [v0.1.7 (1.10.2)](https://github.com/elytra/FruitPhone/releases/tag/1.10.2-0.1.7), and [v0.1.7 (1.7.10)](https://github.com/elytra/FruitPhone/releases/tag/1.7.10-0.1.7).
